variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  # install dependencies
  -
    echo "deb http://httpredir.debian.org/debian/ jessie main contrib" >
      /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - apt-get update -y -qq
  -
    apt-get install -y -qq daemon tcpdump tshark vagrant doxygen cmake
      libnss3-dev libev-dev virtualbox virtualbox-dkms
  - VBoxManage --version

compile:
  stage: build
  script:
  - cmake .
  - make

run:
  stage: test
  script:
  - make test-quickie-client
  - make test-quickie-server
