dist: trusty
sudo: false

language: C
os:
  - linux

branches:
  only:
    - master

env:
  global:
    - secure: "IHICwP4oMbC6yzx9G4YIthU6ujpt0bJ4jOElN7ujs8xGODB7YQFlxIaBwLvCf8APjczUuarN1r0Vc/Ekyp8LVBVdI6oEK0ZyHkvXOsydtYAtKrK60iEZXLoMzqTR/DeZaLkQb/hh4tYLAfrzNs9ZZA6vU1rJUJdaNmxluM9kcF253tfxKZ7rZ8dveD+gwmfJYH47sNwvFiGVTmU6c9fDVVfE/R3c0aX3A4pI3oOAUMH6Vs/76ZdRh2knzLLDgcNiIDapJd1xlw8HFSyEbsfEgTLPl+9qeXyh8fU6kwU7tGKetdr60klrXChIdwqStOxNwp4ylto727oYtztj7zJxYWQxbXQwehH66Xj44KEfW9MEuBEbGCmlR/74vCTNnKVU6D857ZU7r0L43GTD9KfAqqHWKtdQJpoRZMkhRcFrZkHCG8GJJo+3swwXFWnPbqPDuGWnLaeg4dsFpcAhq4ujSFheJbJ+ilERGio8ksv+FndlImSsQVEHtErPyJlizE3y2QfdWfASpn5HYVJ5la0Vy5Tea0rPRymdtLQm3lCMX+qcAg9EQLFHsc52LsFUwnHrNu5WqzfCmN0b7kfT4SlEHVXOXtC6k5PYxAUBaHfyeVFspc4UN5ZTUmSj9Y2h47Oa5KV/DJRaNKalve3TYgysEvlnTqv6qJfqnbHO2Swl+GE="
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "xpuYkQRBKDN0l7S2lVdbBw364qlxg0H7lRW2YroOaUsm1wd4YzzUKsuDG5vIJ0N7WZ0WWaECoa0HMleHVZ5ecY9GmwJ9AfLpfvGrrMyYF1XUkz3C3Xe653nZfK7mGMqPRC6zds5Y05u+goPBidhbXxU7cIS+i6nIrsB5HPa73F3AURNzTQKPfWwYcn3FbmTuheNPT4QujC+tt2g1rEbL5t2io+Hkwy114wntYoHbtbNPi64YorIu1oY9epHPbX61VdCZAuWjjdhn6qCjQaI4k45Bkdr/MDq0YB1cfaIQTOeN8t2EmzKKWufzke+0l7jGM8ISQtCOsQbBgYHb9P8nt6AL+PoxBO6/mMvf2bWOFGzECvEtfpfytBocI+YTsFG555YXGqy7DFYlcEeiyoUW0nTzesckT3n0amLw+TBA6STBw9bqobCAoiLKRg2xbNPMcKQmwuVjt+AFdfEVUUMNgm0z/43gzAkUNy2prH8yEBpcUkm7hpmv7k0dgVHl9OxxhjIIHvQm3LDtMUPmwqAEVGEVI+13DHcVBlzJm5BXqQGIb6q2BGi1WX/FvxiS4W1eRzZnzfnNxkpzcWu/msLhAYfk5vDuhR8k0A345o6vKZwIJC2G3nz5aHS5bdDcV7F/Tb4kAaxgpP/9VbFhE8GddkQzJiUE8mUbHcANyeE/5I0="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - doxygen
      - graphviz
      - libev-dev
      - ninja-build
  coverity_scan:
    project:
      name: "NTAP/quant"
      description: "Build submitted via Travis CI"
    notification_email: lars@netapp.com
    build_command_prepend: "cd $TRAVIS_BUILD_DIR; mkdir build; cd build; cmake -GNinja .; ninja clean"
    build_command: ninja
    branch_pattern: master

script:
  - |
    cd $TRAVIS_BUILD_DIR
    mkdir build
    cd build
    cmake -GNinja -DCMAKE_C_COMPILER=gcc-4.9 ..
    ninja clean
    ninja

after_success:
  # update the documentation
  - |
    cd $TRAVIS_BUILD_DIR/build
    git clone -b gh-pages https://git@github.com/NTAP/quant.git gh-pages
    cd gh-pages
    git config --global push.default simple
    git config user.name "Travis CI"
    git config user.email "travis@travis-ci.org"
    rm -rf ./*
    touch .nojekyll
    doxygen $TRAVIS_BUILD_DIR/build/doc/Doxyfile 2>&1 | tee doxygen.log
    if [ -d "html" ] && [ -f "html/index.html" ]; then
        mv html/* .
        git add --all
        git commit -m "Update doxygen documentation on branch gh-pages." \
            -m "Travis CI build ${TRAVIS_BUILD_NUMBER}." \
            -m "Commit: ${TRAVIS_COMMIT}."
        git push --force https://${GH_REPO_TOKEN}@github.com/NTAP/quant.git > /dev/null 2>&1
    fi
