---
dist: xenial
sudo: false

language: cpp
os:
  - linux

env:
  global:
    - PROJECT=quant
    - secure: "MTff3c4sDIkFqXpYPVjSTc8uJlnfp3OVxcAVTb30yQWqKJ7XWcIEMMPNWPkwxh4UX3mA5rpCMeRyHNzbj+jqPHNKrYr8XxgXHi7zMX92/xrQToZLMFlYEGiae9q7kSwmwPcnDPRibynSoHuULHu+iuAFVe+Sg/NFE/5Ede8fi4lV4j+0pJ/7ruF5zUvcF92drHJL11hxoaQiIlwPto33tsDCAbBPqNpZa1U1Cgs+5WugIgN03Q5Kit8IFO5xZw5PSuVxY/u4E5BzlUU11jFKod7NTuaKTeSt/AJlkgFBbgKdxo7i29ALgWGfS7KZLaoYy3cAMOKwl3K8q71tB1+yl8iH5QF01BmQOzQlX+NZfKCw50HLGLKWBfaPcl2d4mfYkwhys+ocnoISGUF1pqLRiW01sPof7Cy/yHGwlth+Nt9OWC/AUlNv+UZMt9obD5pU6OSJCDrm2K/fQUm+sCpSPrG+565Fcf2Puo2JJvrD9oyYsm2cQ4ztXx9Mc1jHdobkgvOOhCwPiHWPs0DR8lcThznuZ9Y0D29lS+WeC8Bvbe3G4HKndGruAV7X9zDeS9+44H8boXe5o+thFqZVuidRa6FdsWC+t0rH6uc4MBDTSZ42zD6rIRUOpGx6muXdaZFSx2VeTnU6XxNsFfrZRu7aQHmCyTD1NY3gAUv0GcbbT6c="
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "xpuYkQRBKDN0l7S2lVdbBw364qlxg0H7lRW2YroOaUsm1wd4YzzUKsuDG5vIJ0N7WZ0WWaECoa0HMleHVZ5ecY9GmwJ9AfLpfvGrrMyYF1XUkz3C3Xe653nZfK7mGMqPRC6zds5Y05u+goPBidhbXxU7cIS+i6nIrsB5HPa73F3AURNzTQKPfWwYcn3FbmTuheNPT4QujC+tt2g1rEbL5t2io+Hkwy114wntYoHbtbNPi64YorIu1oY9epHPbX61VdCZAuWjjdhn6qCjQaI4k45Bkdr/MDq0YB1cfaIQTOeN8t2EmzKKWufzke+0l7jGM8ISQtCOsQbBgYHb9P8nt6AL+PoxBO6/mMvf2bWOFGzECvEtfpfytBocI+YTsFG555YXGqy7DFYlcEeiyoUW0nTzesckT3n0amLw+TBA6STBw9bqobCAoiLKRg2xbNPMcKQmwuVjt+AFdfEVUUMNgm0z/43gzAkUNy2prH8yEBpcUkm7hpmv7k0dgVHl9OxxhjIIHvQm3LDtMUPmwqAEVGEVI+13DHcVBlzJm5BXqQGIb6q2BGi1WX/FvxiS4W1eRzZnzfnNxkpzcWu/msLhAYfk5vDuhR8k0A345o6vKZwIJC2G3nz5aHS5bdDcV7F/Tb4kAaxgpP/9VbFhE8GddkQzJiUE8mUbHcANyeE/5I0="

addons:
  apt:
    packages:
      - libhttp-parser-dev
      - libbsd-dev
      - cmake
      - openssl
  coverity_scan:
    project:
      name: "NTAP/$PROJECT"
      description: "Build submitted via Travis CI"
    notification_email: lars@netapp.com
    build_command_prepend: cd $TRAVIS_BUILD_DIR && cmake .
    build_command:  make
    branch_pattern: coverity

before_install:
  # manually install latest openssl
  - |
    travis_retry wget \
      -q https://www.openssl.org/source/openssl-1.1.1b.tar.gz
    tar xf openssl-1.1.1b.tar.gz
    cd openssl-1.1.1b
    ./config --openssldir=/usr/local
    sudo make -s install > /dev/null
    sudo ldconfig /usr/local/lib

script: exit 0
