dist: trusty
sudo: false

language: cpp
os:
  - linux

branches:
  only:
    - master

env:
  matrix:
    global:
      - BUILD_TYPE=Debug    MYCC=gcc-7      MYCXX=g++-7
      - BUILD_TYPE=Release  MYCC=gcc-7      MYCXX=g++-7
      - BUILD_TYPE=Debug    MYCC=clang-5.0  MYCXX=clang++-5.0
      - BUILD_TYPE=Release  MYCC=clang-5.0  MYCXX=clang++-5.0
  global:
    - PROJECT=quant
    - secure: "IHICwP4oMbC6yzx9G4YIthU6ujpt0bJ4jOElN7ujs8xGODB7YQFlxIaBwLvCf8APjczUuarN1r0Vc/Ekyp8LVBVdI6oEK0ZyHkvXOsydtYAtKrK60iEZXLoMzqTR/DeZaLkQb/hh4tYLAfrzNs9ZZA6vU1rJUJdaNmxluM9kcF253tfxKZ7rZ8dveD+gwmfJYH47sNwvFiGVTmU6c9fDVVfE/R3c0aX3A4pI3oOAUMH6Vs/76ZdRh2knzLLDgcNiIDapJd1xlw8HFSyEbsfEgTLPl+9qeXyh8fU6kwU7tGKetdr60klrXChIdwqStOxNwp4ylto727oYtztj7zJxYWQxbXQwehH66Xj44KEfW9MEuBEbGCmlR/74vCTNnKVU6D857ZU7r0L43GTD9KfAqqHWKtdQJpoRZMkhRcFrZkHCG8GJJo+3swwXFWnPbqPDuGWnLaeg4dsFpcAhq4ujSFheJbJ+ilERGio8ksv+FndlImSsQVEHtErPyJlizE3y2QfdWfASpn5HYVJ5la0Vy5Tea0rPRymdtLQm3lCMX+qcAg9EQLFHsc52LsFUwnHrNu5WqzfCmN0b7kfT4SlEHVXOXtC6k5PYxAUBaHfyeVFspc4UN5ZTUmSj9Y2h47Oa5KV/DJRaNKalve3TYgysEvlnTqv6qJfqnbHO2Swl+GE="
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "xpuYkQRBKDN0l7S2lVdbBw364qlxg0H7lRW2YroOaUsm1wd4YzzUKsuDG5vIJ0N7WZ0WWaECoa0HMleHVZ5ecY9GmwJ9AfLpfvGrrMyYF1XUkz3C3Xe653nZfK7mGMqPRC6zds5Y05u+goPBidhbXxU7cIS+i6nIrsB5HPa73F3AURNzTQKPfWwYcn3FbmTuheNPT4QujC+tt2g1rEbL5t2io+Hkwy114wntYoHbtbNPi64YorIu1oY9epHPbX61VdCZAuWjjdhn6qCjQaI4k45Bkdr/MDq0YB1cfaIQTOeN8t2EmzKKWufzke+0l7jGM8ISQtCOsQbBgYHb9P8nt6AL+PoxBO6/mMvf2bWOFGzECvEtfpfytBocI+YTsFG555YXGqy7DFYlcEeiyoUW0nTzesckT3n0amLw+TBA6STBw9bqobCAoiLKRg2xbNPMcKQmwuVjt+AFdfEVUUMNgm0z/43gzAkUNy2prH8yEBpcUkm7hpmv7k0dgVHl9OxxhjIIHvQm3LDtMUPmwqAEVGEVI+13DHcVBlzJm5BXqQGIb6q2BGi1WX/FvxiS4W1eRzZnzfnNxkpzcWu/msLhAYfk5vDuhR8k0A345o6vKZwIJC2G3nz5aHS5bdDcV7F/Tb4kAaxgpP/9VbFhE8GddkQzJiUE8mUbHcANyeE/5I0="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      # quant needs Generic macros, which aren't in 4.8
      - g++-7
      - clang-5.0
      - doxygen
      - graphviz
      - ninja-build
      - libev-dev
      - libhttp-parser-dev
  coverity_scan:
    project:
      name: "NTAP/$PROJECT"
      description: "Build submitted via Travis CI"
    notification_email: lars@netapp.com
    build_command_prepend: |
      cd $TRAVIS_BUILD_DIR
      rm -rf build
      mkdir build
      cd build
      ../bin/cmake -GNinja -DCMAKE_C_COMPILER=$MYCC \
        -DCMAKE_CXX_COMPILER=$MYCXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
        -DCMAKE_INSTALL_PREFIX:PATH=/tmp ..
    build_command: ninja
    branch_pattern: coverity

before_install:
  # manually install latest cmake
  - |
    wget -q https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.sh
    sh cmake-3.9.4-Linux-x86_64.sh --skip-license

script:
  - |
    if [ "${COVERITY_SCAN_BRANCH}" = 1 ]; then exit 0 ; fi
    cd $TRAVIS_BUILD_DIR
    rm -rf build
    mkdir build
    cd build
    ../bin/cmake -GNinja -DCMAKE_C_COMPILER=$MYCC \
      -DCMAKE_CXX_COMPILER=$MYCXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
      -DCMAKE_INSTALL_PREFIX:PATH=/tmp ..
    ninja

after_success:
  # update the documentation
  - |
    cd $TRAVIS_BUILD_DIR/build
    git clone -b gh-pages https://git@github.com/NTAP/$PROJECT.git gh-pages
    cd gh-pages
    git config --global push.default simple
    git config user.name "Travis CI"
    git config user.email "travis@travis-ci.org"
    rm -rf ./*
    touch .nojekyll
    doxygen $TRAVIS_BUILD_DIR/build/doc/Doxyfile 2>&1 | tee doxygen.log
    if [ -d "html" ] && [ -f "html/index.html" ]; then
        mv html/* .
        git add --all
        git commit -m "Update doxygen documentation on branch gh-pages." \
            -m "Travis CI build ${TRAVIS_BUILD_NUMBER}." \
            -m "Commit: ${TRAVIS_COMMIT}."
        git push --force \
          https://${GH_REPO_TOKEN}@github.com/NTAP/$PROJECT.git > /dev/null 2>&1
    fi
