dist: trusty
language: C

branches:
  only:
    - master

env:
  global:
    - secure: "UDnnm19C/WmuLCMYtJ255REoKl8fH7buGZC2b0VXa/Uf201KXjd9eN2Ow2/FqJc5PiKbH+CR54z9Df+1bhaAyORQmsRpfoVpBlzbp7IHKRP6MV3djm/B8ZJVKcfd9PdNrba5Wnf1cH/z0aBg1GtDouXoAqgawjiVYrAS2qxUoH7c0064DgJ+mDPtigrHmbanoSWfs8hyvVrgCJeNa8HjYoHeoi78AJAZ+jjTYcnWIJumSGKiFpmlNM/4YWROBYIuo++fH3rcsmyzGoUZkGOoLGg1Ja3t2tvkbHDS+oNGPZvYEmWwAKwJXEqWzrkME1TGfmafIgHnsuaUhbAWQh56XdVlzvvIH+KlzmwfFpL6FZacegDQS7F8AjLz2X+WbvyVUrnGs43RpUfZtHNCXfFnqiSxr1YF7MctG9PM0K6x+2OIhvCT9J4cto1dIPU0EIe62OEFeFCWkMtjdmAIHxSm1S3lCflX178DnbpVmaaQcmpihKR71739ztCL3y50gA44Bg0IQP+TPwfyZz7H2t7QJbRrsxbT8akwq04wmLCplX4VDBx4XScXe3k9oHZBznj02vN+6fsX5tLciP6oPJYtf/VgnDwUkzPKr86SAz1q3NfZxIHBfBivoU/sEQPbgp3fEFY7bPijgIqC/Q/ZRKGCiP0EOBlYVKroDydHMh50Ojw="

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - libev-dev

script:
  - cmake .
  - git clone -b gh-pages https://git@github.com/NTAP/quant.git gh-pages
  - cd gh-pages
  - rm -rf ./*
  - touch .nojekyll
  - doxygen $TRAVIS_BUILD_DIR/doc/Doxyfile
