# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:
    sudo apt-get -y install git cmake libssl-dev g++ libhttp-parser-dev pkg-config 
  displayName: 'apt'
- script: |
    mkdir build
    cd build
    cmake ..
    make
  displayName: 'make'

