# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:
    sudo apt-get -y install git cmake libssl-dev g++ libhttp-parser-dev pkg-config 
  displayName: 'apt'
- script:
    mkdir -p build
    cd build
    cmake ..
    make
  displayName: 'make'

