version: "3"
services:

  server:
    image: ntap/quant
    expose:
      - 4433
    command: server -i eth0 -d /www -c /tls/quant.crt -k /tls/quant.key -v4

  valve:
    depends_on:
      - server
    image: larseggert/qvalve
    tty: true
    expose:
      - 4433
    volumes:
      - ../qvalve:/qvalve-dev:ro
    working_dir: /qvalve-dev
    command: ./qvalve.py -ra server -t tests/demo.qv

  client:
    depends_on:
      - server
      - valve
    image: ntap/quant
    command: client -v4 -i eth0 https://valve/index.html
