version: "3"
services:

  client:
    image: ntap/quant
    command: >
        client -v4 -i eth0 https://valve/index.html

  server:
    image: ntap/quant
    expose:
      - 4433
    command: >
        server -i eth0 -d /www -c /tls/quant.crt -k /tls/quant.key -v4

  valve:
    image: larseggert/qvalve
    tty: true
    expose:
      - 4433
    command: >
        /qvalve/qvalve.py -fa server

