version: "3"
services:

  server:
    image: ntap/quant
    expose:
      - 4433
    command: >
        server -i eth0 -d /www -c /tls/quant.crt -k /tls/quant.key -v4

  valve:
    depends_on:
      - server
    image: larseggert/qvalve
    tty: true
    expose:
      - 4433
    volumes:
      - ../qvalve:/qvalve-dev:ro
    command: >
        /qvalve-dev/qvalve.py -ra server

  client:
    depends_on:
      - server
      - valve
    image: ntap/quant
    command: >
        client -v4 -i eth0 https://valve/index.html

